### ISSUE TITLE
ignore password

### ISSUE THREAD

**Issue by muelli** [ehuggett/send-cli#13]
I usually don't want to set a password. I'd appreciate if I could make send-cli not ask me for one. Actually, I'm surprised to see that asking for a password is the default. It's optional by default in the Web interface.

**Comment by ehuggett** [comment]
I've been thinking that,
`send-cli file` should ask if you want a password, to set the download limit (etc)
`send-cli --file file` should upload the file with no further questions*

How does that sound to you?

*`--password yes|no` should probably be added to allow a password to be specified. I would still ask/prompt for the password because, so far as I know, there is no safe way of specifying it on the command line.

**Comment by muelli** [comment]
> send-cli file should ask if you want a password, to set the download limit (etc)

Hrm. I think that should be as convenient and as fire-and-forget as possible. My goal, most often, is to quickly share a file with someone.  I then pull up a terminal and type "send-cli" and tab my way to the file or drag-n-drop it from a file manager.  For my particular usage pattern any interactiveness is bad, as are more flag that I would have to type.

**Comment by ehuggett** [comment]
I was hesitant to respond before i had time to properly consider if I only still wanted to do it this way because its what I had assumed I would do from the beginning! Apologies for the delay

- I'm still erring towards prompting for confirmation before uploading, The general idea was if you don't tell send-cli what to do then it should ask
  - I've been meaning to add an extra prompt to uploading without flags for awhile https://github.com/ehuggett/send-cli/blob/5149bfb4fc20264c601790f4efdf152110e9347b/scripts/send-cli#L105
- I want send-cli to be as simple as possible to use, I don't think the "ask questions mode" should be hidden behind a flag.
- To focus on your point about convenience, having to specify `--download-limit XX  --password` if you do want a password and a non-default download limit is not very convenient, even if it was `-l XX -p` i suspect some people would prefer to answer the questions
- Short options still need to be added (`-f` is a little more convenient that `--file`), but I've been hesitant to do this this so far as I don't want to change what any option does after I have assigned it. 
- Shell aliases are often a good way to avoid having to type options/flags 

_Off topic: For part of your use case, it would be interesting to integrate send-cli into a file managers context menu (right click, upload to Send), either by opening a shell (that should remain open after send-cli exits) or displaying the link with zenity/etc (but displaying progress is probably essential for larger files) . I'll add it to the README if i get around to trying it_ .

**Comment by muelli** [comment]
On Tue, 2018-01-30 at 12:24 -0800, ehuggett wrote:
> I'm still erring towards prompting for confirmation before uploading,
> The general idea was if you don't tell send-cli what to do then it
> should ask
I guess we just disagree here what the desired behaviour is.


> I've been meaning to add an extra prompt to uploading without flags
> for awhile https://github.com/ehuggett/send-
> cli/blob/5149bfb4fc20264c601790f4efdf152110e9347b/scripts/send-
> cli#L105
> I want send-cli to be as simple as possible to use,
heh. Now the question is whether the tool just doing its things makes it
easier to use than prompting the user for questions they might not be
able to answer.
I strongly believe that getting out of the way and just doing the job
makes it easier to use than *having* to answer questions.

>  I don't think the "ask questions mode" should be hidden behind a
> flag.
how many questions could you potentially ask?
I'm surprised to see that there is a password, because I don't remember
the Web interface exposing that at all.
And if there are no more questions then your concern magically 

> To focus on your point about convenience, having to specify --
> download-limit XX --password if you do want a password and a non-
> default download limit is not very convenient, even if it was -l XX -p
> i suspect some people would prefer to answer the questions
Downloading may be a different use case and it may be sensible to have
separate programs for that. Do one thing and do it well.
And I care for the upload tool only. I've never used "send(!)-cli" to
retrieve a file.


> Shell aliases are often a good way to avoid having to type
> options/flags
sure. So are custom programs around libraries. But the fewer such hacks
are necessary, the happier my life will be.
And in general, prompts make me very unhappy.

If the prompts in send-cli won't go away, then maybe I can persuade you
to make it read a configuration file s.t. I can make it not ask for a
password.

> Off topic: For part of your use case, it would be interesting to
> integrate send-cli into a file managers context menu (right click,
> upload to Send), either by opening a shell (that should remain open
> after send-cli exits) or displaying the link with zenity/etc (but
> displaying progress is probably essential for larger files) . I'll add
> it to the README if i get around to trying it .
True. Maybe we can do it as part of a GNOME Summer of Code.

**Comment by ehuggett** [comment]
I keep coming back to this point (I can think of a few features that Send might gain over time)

> how many questions could you potentially ask?

I was intending to also ask for the Download limit #8.

Following the same pattern if Send added further options would not be desirable (as default behaviour), even if you could always hit enter to accept the defaults (no password, download limit 1, etc) that would definitely be inconvenient!

One seemed ok, I'm now very unsure about two and as there is a chance for 3 its probably to stop prompting by default now so the behaviour of send-cli doesn't need to change significantly in the future

- Add `--password`, using this option when uploading a file should cause send-cli to prompt the user for a password.

**Comment by ehuggett** [comment]
send-cli no longer prompts for a password when uploading a file (unless you request it with `--password`).
